apiVersion: v1
appVersion: "1.14"
description: Telegraf is an agent written in Go for collecting, processing, aggregating,
  and writing metrics.
home: https://www.influxdata.com/time-series-platform/telegraf/
keywords:
- telegraf
- collector
- timeseries
- influxdata
maintainers:
- email: rawkode@influxdata.com
  name: rawkode
- email: giacomo@influxdata.com
  name: gitirabassi
- email: naseemkullah@gmail.com
  name: naseemkullah
- email: contact@cerenit.fr
  name: nsteinmetz
name: telegraf-ds
version: 1.0.6
