{
 "title": "bep_detail",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Nodes",
    "query": "SHOW tag values ON \"telegraf\" FROM \"kubernetes_node\" with key = \"node_name\";"
   },
   {
    "name": "Containers",
    "query": "SHOW tag values ON \"telegraf\" FROM \"kubernetes_pod_container\" with key = \"container_name\";"
   },
   {
    "name": "Pods",
    "query": "SHOW tag values ON \"telegraf\" FROM \"kubernetes_pod_container\" with key = \"pod_name\";"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"cpu_usage_nanocores\") /10000000 FROM \"kubernetes_pod_container\" WHERE $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/10000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pod_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"cpu_usage_nanocores\") /10000000 FROM \"kubernetes_pod_container\" WHERE $timeFilter GROUP BY time($__interval), \"pod_name\" fill(null)",
     "select": [
      [
       { "params": [ "memory_rss_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "👀",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT mean(\"cpu_usage_nanocores\") /10000000 FROM \"kubernetes_node\" WHERE (\"node_name\" =~ /^$Nodes$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/10000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=", "value": "pool-liqker5cu-3ubnw" }
     ]
    }
   ]
  },
  {
   "title": "Node RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "query": "SELECT (mean(\"memory_usage_bytes\")  / (mean(\"memory_usage_bytes\") + mean(\"memory_available_bytes\")))*100  FROM \"kubernetes_node\" WHERE (\"node_name\" =~ /^$Nodes$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_usage_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "node_name", "operator": "=", "value": "pool-liqker5cu-3ubnw" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "query": "SELECT mean(\"cpu_usage_nanocores\") /10000000 FROM \"kubernetes_pod_container\" WHERE (\"container_name\" =~ /^$Containers$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_nanocores" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/10000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Container RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_rss_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Container RAM usage (per 500Mb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "memory_rss_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 5000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$Containers$/" }
     ]
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Receive bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_network",
     "query": "SELECT last(\"rx_bytes\") FROM \"kubernetes_pod_network\" WHERE (\"pod_name\" = 'bep-grafana-6548c6965b-nphzw') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pod_name", "operator": "=", "value": "bep-grafana-6548c6965b-nphzw" }
     ]
    },
    {
     "alias": "Send bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"tx_bytes\")  FROM \"kubernetes_pod_network\" WHERE (\"pod_name\" = 'bep-grafana-6548c6965b-nphzw') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}